# Generated by Django 5.0.6 on 2024-07-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_of_work_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Объект АСУТП',
                'verbose_name_plural': 'Объекты АСУТП',
            },
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_status_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Секторы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
                ('sector_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.sector')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField(max_length=1000, verbose_name='Введите название задачи')),
                ('control_date', models.DateField(default=0, verbose_name='Контрольный срок')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления задачи')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='Дата завершения задачи')),
                ('object_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.objectofwork', verbose_name='Объект АСУТП')),
                ('problem_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.problemstatus', verbose_name='Выберите статус задачи')),
                ('problem_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.problemtype', verbose_name='Выберите тип мероприятия')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.staff', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
