# Generated by Django 4.2.14 on 2024-07-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemtype',
            options={'verbose_name': 'Категория задачи', 'verbose_name_plural': 'Категории задач'},
        ),
        migrations.AlterField(
            model_name='objectofwork',
            name='object_of_work_text',
            field=models.CharField(max_length=200, verbose_name='Объект производства работ'),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='problem_status_text',
            field=models.CharField(max_length=200, verbose_name='Статус выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='problem_type_text',
            field=models.CharField(max_length=200, verbose_name='Категория задачи'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_text',
            field=models.CharField(max_length=200, verbose_name='Сектор сотрудника'),
        ),
    ]
