# Generated by Django 4.2.14 on 2024-08-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sector_id',
            new_name='sector',
        ),
    ]
