# Generated by Django 4.2.14 on 2024-08-23 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sector_id_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 8, 23), verbose_name='День рождения'),
        ),
    ]
