# Generated by Django 4.2.14 on 2024-07-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_problemtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.sector', verbose_name='Сектор сотрудника'),
        ),
    ]
