# Generated by Django 4.2.14 on 2024-08-20 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата завершения задачи'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 8, 20), verbose_name='День рождения'),
        ),
    ]
