# Generated by Django 4.2.14 on 2024-07-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staff_sector_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='object_of_work',
            new_name='object_of_work_id',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_status',
            new_name='problem_status_id',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_type',
            new_name='problem_type_id',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
