# Generated by Django 4.2.14 on 2024-08-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_problem_end_date_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='end_date',
        ),
    ]
