# Generated by Django 4.2.14 on 2024-08-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_object_of_work_problem_object_of_work_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='control_date',
            field=models.DateTimeField(default=0, verbose_name='Контрольный срок'),
        ),
    ]
