# Generated by Django 4.2.14 on 2024-08-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_problem_control_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='object_of_work_id',
            new_name='object_of_work',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_status_id',
            new_name='problem_status',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_type_id',
            new_name='problem_type',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
