# Generated by Django 4.2.14 on 2024-08-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_object_of_work_id_problem_object_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='object_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.objectofwork', verbose_name='Объект АСУТП'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Ответственный сотрудник'),
        ),
    ]
