# Generated by Django 4.2.14 on 2024-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_problem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='add_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата добавления задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения задачи'),
        ),
    ]
