# Generated by Django 4.2.14 on 2024-08-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_problem_add_date_alter_problem_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='control_date',
            field=models.DateField(default=0, verbose_name='Контрольный срок'),
        ),
    ]
