# Generated by Django 4.2.14 on 2024-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_problem_control_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(default=0, verbose_name='Дата завершения задачи'),
        ),
    ]
