# Generated by Django 4.2.14 on 2024-08-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_problem_add_date_alter_problem_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='end_date',
        ),
    ]
