# Generated by Django 4.2.14 on 2024-08-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_staff_user_alter_problem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
